- name: install cron job (andible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "HOME=/home/ansible /usr/bin/ansible-pull -o -U https://github.com/mille535/ansible-pull-playground.git -d /home/ansible/.ansible/pull > /dev/null"
