- name: install cron job (andible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://codeberg.org/millk/ansible-push.git > /dev/null"
