- name: Install packages
  pacman:
    name:
      - btop
      - sudo
      #- yazi
      - fzf
      #- 7zip
      #- ffmpeg
      #- lazygit
      #- lazydocker
      #- ghostty
      - zsh
      - nvim
      - git
      - tmux
      - tree-sitter-cli #kickstart.nvim dep
      - base-devel
