- name: Install packages
  pacman:
    name:
      - btop
      - sudo
      #- yazi
      #- fzf
      #- 7zip
      #- ffmpeg
      #- lazygit
      #- lazydocker
      #- ghostty
      - nvim
      - git
      - tmux
