- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: change ansible.log ownership to ansible servuce user
  file:
    path: /var/log/ansible.log
    owner: ansible
    group: ansible
    mode: 0644

- name: "Create group: sudo"
  group:
    name: sudo
    state: present

- name: "Create group: Kirk"
  group:
    name: kirk
    state: present

- name: "Create user: Kirk"
  user:
    name: kirk
    group: kirk
    groups: sudo
    state: present
    comment: "Kirk Miller"
    password: "$6$FLh7YLSu2g/iD1M3$IT0/X.v6e/ryoqrO2yktbZAMH9l0H77uHdlkxjRMHd1K5uG/Bgj/sGwJVd2sxn12v55OZl7Cwnv9e60cKZD3y0"
    shell: /bin/zsh

- name: copy sudoers_kirk
  copy:
    src: files/sudoers_kirk
    dest: /etc/sudoers.d/kirk
    owner: root
    group: root
    mode: 0440

- name: create nvim config dir
  file:
    path: /home/kirk/{{ item.dir }}
    state: directory
    owner: kirk
    group: kirk
    mode: 0755
  with_items:
    - { dir: '.config/nvim' }
    - { dir: '.zsh' }

- name: pull in kickstart.nvim for Kirk
  become: true
  become_user: kirk
  git:
    repo: https://github.com/mille535/kickstart.nvim.git
    dest: /home/kirk/.config/nvim
